sonar.projectKey=mathiasconradt_sonarqube-sbom-visualization-plugin
sonar.organization=mathiasconradt
sonar.projectName=SonarQube SBOM Visualization Plugin

sonar.sources=src/main/java,src/main/resources/static
sonar.java.binaries=target/classes

sonar.exclusions=src/main/resources/static/echarts.min.js
